### ISSUE TITLE
root tree manually

### ISSUE THREAD

**Issue by noraheaphy** [noraheaphy/finalproject#2]
Hi @caseywdunn and @lemellenthin,

I've been rooting the Portulaca phylogeny I received from the Edwards Lab manually in R using `portulacaTree <- root(portulacaTree, node = 28, edgelabel = TRUE)` because although the .treefile came unrooted, I know where the root should be based on Ocampo & Columbus (2012), as this tree is a replicate of their methods. But now I'm having doubts that this is okay, because am I right in thinking that internal node numbers are assigned randomly and node 28 may not refer to the same place in the tree each time I pull files in and mess around with the code? Is there a way to root the tree always in the same place in a more generalizable way? Or perhaps easiest thing would be to edit the NEXUS file somehow to specify the root?

This is `Line 122` of [port_ancestral_reconstruct.Rmd](https://github.com/noraheaphy/finalproject/blob/master/port_ancestral_reconstruct.Rmd) based on the tree in [Ocampo_Portulaca.parts.treefile](https://github.com/noraheaphy/finalproject/blob/master/data/Ocampo_Portulaca.parts.treefile) and the character data in [portulaca_means_11-06-2020.csv](https://github.com/noraheaphy/finalproject/blob/master/data/portulaca_means_11-06-2020.csv). 

I've attached a picture of where the tree ought to be rooted. In my current interface, that's node 49, but it may not be the same for you.
<img width="457" alt="port_phylo_root" src="https://user-images.githubusercontent.com/69914585/100550847-c17b8b00-324a-11eb-91f2-8c628ccfa655.png">

Thanks so much!

Nora

**Comment by caseywdunn** [comment]
You are completely correct- it is good practice to not root explicitly be internal node number. In my experience it does work consistently on the same version of the software on the same system, but there is no guarantee of this.

I like to get the number of the node to root on using `getmrca()`, and specifying tip names. Then I use that number to root. This is much more robust. So you would pick a couple of taxa that span the full ingroup, use them to retrieve the number of the root, then root on the node with that number.

The code in exercise 2 covers some of this - https://github.com/Yale-EEB354/autograder/blob/62c2ab1b24bf0eb508810d15596a224e5cea5137/exercise_02/exercise_02.rmd#L124
